source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.0’
use_frameworks!

target ‘Copenhacks2017’ do
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftyJSON'
    pod 'Hero'
    pod 'SwipeCellKit'
    pod 'DatePickerDialog'
end